-- Additive historical-sales import foundation. Existing catalog, stock, sales, and forecasts are preserved.
CREATE TABLE `historical_sales_import_batches` (
  `id` VARCHAR(191) NOT NULL,
  `batch_code` VARCHAR(80) NOT NULL,
  `original_file_name` VARCHAR(255) NOT NULL,
  `file_hash` VARCHAR(64) NOT NULL,
  `file_type` VARCHAR(16) NOT NULL,
  `file_size` INTEGER UNSIGNED NOT NULL,
  `import_mode` ENUM('APPEND_ONLY', 'REJECT_ON_OVERLAP', 'REPLACE_IMPORTED_OVERLAPS') NOT NULL DEFAULT 'APPEND_ONLY',
  `status` ENUM('PREVIEWED', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_SKIPS', 'FAILED', 'ROLLED_BACK') NOT NULL DEFAULT 'PREVIEWED',
  `total_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `valid_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `invalid_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `matched_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `unmatched_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `duplicate_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `overlap_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `pos_overlap_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `imported_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `skipped_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `replaced_rows` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `products_affected` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `forecast_refresh_status` ENUM('NOT_REQUIRED', 'PENDING', 'SUCCEEDED', 'FAILED') NOT NULL DEFAULT 'NOT_REQUIRED',
  `imported_by_user_id` VARCHAR(191) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `confirmed_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `failed_at` DATETIME(3) NULL,
  `rolled_back_at` DATETIME(3) NULL,
  `rolled_back_by_user_id` VARCHAR(191) NULL,
  `rollback_reason` VARCHAR(500) NULL,
  `error_message` VARCHAR(500) NULL,
  `metadata` JSON NULL,
  UNIQUE INDEX `uq_historical_import_batch_code`(`batch_code`),
  INDEX `idx_historical_import_file_hash_status`(`file_hash`, `status`),
  INDEX `idx_historical_import_status_created`(`status`, `created_at`),
  INDEX `idx_historical_import_user_created`(`imported_by_user_id`, `created_at`),
  INDEX `idx_historical_import_rollback_user`(`rolled_back_by_user_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `historical_import_imported_by_fkey` FOREIGN KEY (`imported_by_user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `historical_import_rolled_back_by_fkey` FOREIGN KEY (`rolled_back_by_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `historical_monthly_sales` (
  `id` VARCHAR(191) NOT NULL,
  `product_id` VARCHAR(191) NOT NULL,
  `period` DATE NOT NULL,
  `quantity_sold` INTEGER UNSIGNED NOT NULL,
  `unit_price` DECIMAL(10,2) NULL,
  `sales_amount` DECIMAL(12,2) NULL,
  `source` ENUM('IMPORTED_HISTORICAL', 'POS_ACTUAL', 'DEVELOPMENT_FIXTURE') NOT NULL,
  `import_batch_id` VARCHAR(191) NULL,
  `active_key` VARCHAR(255) NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `replaces_record_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `invalidated_at` DATETIME(3) NULL,
  `invalidated_by_user_id` VARCHAR(191) NULL,
  `invalidation_reason` VARCHAR(500) NULL,
  UNIQUE INDEX `uq_historical_monthly_sales_active_key`(`active_key`),
  UNIQUE INDEX `uq_historical_monthly_sales_replaces`(`replaces_record_id`),
  INDEX `idx_historical_monthly_product_period_source_active`(`product_id`, `period`, `source`, `is_active`),
  INDEX `idx_historical_monthly_batch_active`(`import_batch_id`, `is_active`),
  INDEX `idx_historical_monthly_period_source_active`(`period`, `source`, `is_active`),
  INDEX `idx_historical_monthly_invalidated_by`(`invalidated_by_user_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `historical_monthly_product_fkey` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `historical_monthly_batch_fkey` FOREIGN KEY (`import_batch_id`) REFERENCES `historical_sales_import_batches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `historical_monthly_invalidated_by_fkey` FOREIGN KEY (`invalidated_by_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `historical_monthly_replaces_fkey` FOREIGN KEY (`replaces_record_id`) REFERENCES `historical_monthly_sales`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `historical_sales_import_rows` (
  `id` VARCHAR(191) NOT NULL,
  `import_batch_id` VARCHAR(191) NOT NULL,
  `row_number` INTEGER UNSIGNED NOT NULL,
  `raw_data` JSON NOT NULL,
  `normalized_sku` VARCHAR(80) NULL,
  `normalized_barcode` VARCHAR(80) NULL,
  `normalized_period` DATE NULL,
  `quantity_sold` INTEGER UNSIGNED NULL,
  `unit_price` DECIMAL(10,2) NULL,
  `sales_amount` DECIMAL(12,2) NULL,
  `status` ENUM('VALID', 'WARNING', 'INVALID', 'UNMATCHED', 'DUPLICATE', 'OVERLAP', 'IMPORTED', 'SKIPPED', 'REPLACED') NOT NULL,
  `error_code` VARCHAR(80) NULL,
  `error_message` VARCHAR(500) NULL,
  `warning_codes` JSON NULL,
  `matched_product_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `uq_historical_import_row_number`(`import_batch_id`, `row_number`),
  INDEX `idx_historical_import_rows_batch_status_row`(`import_batch_id`, `status`, `row_number`),
  INDEX `idx_historical_import_rows_product_period`(`matched_product_id`, `normalized_period`),
  PRIMARY KEY (`id`),
  CONSTRAINT `historical_import_rows_batch_fkey` FOREIGN KEY (`import_batch_id`) REFERENCES `historical_sales_import_batches`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `historical_import_rows_product_fkey` FOREIGN KEY (`matched_product_id`) REFERENCES `products`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `forecast_records` ADD COLUMN `source_import_batch_id` VARCHAR(191) NULL;
CREATE INDEX `idx_forecasts_source_import_batch` ON `forecast_records`(`source_import_batch_id`);
ALTER TABLE `forecast_records` ADD CONSTRAINT `forecast_records_source_import_batch_fkey` FOREIGN KEY (`source_import_batch_id`) REFERENCES `historical_sales_import_batches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
