from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from statistics import median
from time import monotonic
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    mean_absolute_error,
    mean_absolute_percentage_error,
    root_mean_squared_error,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
FORECAST_ROOT = REPO_ROOT / "forecasting-service"
if str(FORECAST_ROOT) not in sys.path:
    sys.path.insert(0, str(FORECAST_ROOT))

from app.sarima import CANDIDATES, SarimaResult, _fit_candidate, _fit_timeout_seconds  # noqa: E402

REQUIRED_COLUMNS = {
    "product_id",
    "product_name",
    "category",
    "period",
    "quantity_sold",
}

# Thesis-only tuning family. The final five-month hold-out is never used to
# choose among these models; selection is performed only inside the 19-month
# training window.
VALIDATION_CANDIDATES: tuple[
    tuple[tuple[int, int, int], tuple[int, int, int]], ...
] = (
    ((0, 0, 0), (0, 1, 0)),
    ((1, 0, 0), (0, 1, 0)),
    ((0, 0, 1), (0, 1, 0)),
    ((1, 0, 1), (0, 1, 0)),
    ((0, 1, 0), (0, 1, 0)),
    ((0, 1, 1), (0, 1, 0)),
    ((1, 1, 0), (0, 1, 0)),
    ((1, 1, 1), (0, 1, 0)),
    ((0, 1, 1), (0, 1, 1)),
    ((1, 1, 0), (0, 1, 1)),
    ((1, 0, 0), (1, 0, 0)),
    ((1, 0, 1), (1, 0, 0)),
    ((0, 1, 1), (1, 0, 0)),
    ((1, 1, 0), (1, 0, 0)),
    ((0, 1, 1), (0, 0, 0)),
    ((1, 1, 0), (0, 0, 0)),
)


@dataclass
class ProductResult:
    product_id: str
    product_name: str
    category: str
    observations: int
    training_observations: int
    testing_observations: int
    training_start: str
    training_end: str
    testing_start: str
    testing_end: str
    order: str
    seasonal_order: str
    aic: float
    converged: bool
    mae: float
    mape: float | None
    rmse: float
    mape_valid_observations: int
    zero_actual_observations: int
    selection_mode: str
    transform: str
    inner_mape: float | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Chronological SARIMA hold-out validation for YsabelleStore thesis evidence."
    )
    parser.add_argument(
        "--input",
        default="testing/thesis-validation/data/effective_monthly_sales.csv",
        help="CSV generated by thesis:sarima:export.",
    )
    parser.add_argument(
        "--output",
        default="testing/thesis-validation/evidence/sarima",
        help="Directory for CSV, JSON, TXT, and PNG evidence.",
    )
    parser.add_argument(
        "--holdout",
        type=int,
        default=5,
        help="Most recent completed months reserved for testing. Thesis protocol default: 5.",
    )
    parser.add_argument(
        "--min-train",
        type=int,
        default=19,
        help="Minimum training observations for the thesis-only retrospective backtest. Default: 19.",
    )
    parser.add_argument(
        "--seasonal-period",
        type=int,
        default=12,
        help="Seasonal period. Monthly annual seasonality uses 12.",
    )
    parser.add_argument(
        "--plot-product-id",
        default=None,
        help="Optional product ID for product-level figures. Otherwise median-MAPE product is selected deterministically.",
    )
    parser.add_argument(
        "--target-accuracy",
        type=float,
        default=90.0,
        help=(
            "Study target expressed using the project's derived accuracy proxy "
            "(100 - MAPE). Default: 90.0. This does not replace MAE/MAPE/RMSE."
        ),
    )
    parser.add_argument(
        "--selection-mode",
        choices=("aic", "inner-mape"),
        default="aic",
        help=(
            "Model-selection rule. 'aic' reproduces the baseline protocol. "
            "'inner-mape' chooses a SARIMA variant using only an inner hold-out "
            "inside the training window; the final five months remain untouched."
        ),
    )
    parser.add_argument(
        "--inner-holdout",
        type=int,
        default=4,
        help="Training-only validation months used by --selection-mode inner-mape. Default: 4.",
    )
    parser.add_argument(
        "--use-log1p",
        action="store_true",
        help=(
            "Also evaluate log1p-transformed SARIMA variants during training-only "
            "model selection. Forecasts are inverse-transformed before scoring."
        ),
    )
    return parser.parse_args()


def ensure_continuous_months(periods: pd.Series) -> bool:
    if periods.empty:
        return False
    parsed = pd.PeriodIndex(periods.astype(str), freq="M")
    expected = pd.period_range(parsed.min(), parsed.max(), freq="M")
    return parsed.is_unique and list(parsed) == list(expected)


def _validation_timeout_seconds() -> float:
    raw = os.getenv("SARIMA_VALIDATION_TIMEOUT_SECONDS", "20")
    try:
        value = float(raw)
    except ValueError:
        value = 20.0
    return max(2.0, min(value, 90.0))


def _inverse_optional(value: float | None, transform: str) -> float | None:
    if value is None:
        return None
    if transform == "log1p":
        return max(0.0, float(np.expm1(value)))
    return max(0.0, float(value))


def _fit_variant(
    series: pd.Series,
    horizon: int,
    order: tuple[int, int, int],
    seasonal_order: tuple[int, int, int, int],
    deadline: float,
    transform: str,
) -> SarimaResult:
    fit_series = (
        pd.Series(
            np.log1p(series.to_numpy(dtype=float)),
            index=series.index,
            dtype="float64",
        )
        if transform == "log1p"
        else series
    )
    result = _fit_candidate(
        fit_series,
        horizon,
        order,
        seasonal_order,
        deadline,
    )
    if transform != "log1p":
        return result

    return SarimaResult(
        forecast=[
            round(max(0.0, float(np.expm1(value))), 4)
            for value in result.forecast
        ],
        lower=[
            None if value is None else round(_inverse_optional(value, transform) or 0.0, 4)
            for value in result.lower
        ],
        upper=[
            None if value is None else round(_inverse_optional(value, transform) or 0.0, 4)
            for value in result.upper
        ],
        fitted=[float(np.expm1(value)) for value in result.fitted],
        order=result.order,
        seasonal_order=result.seasonal_order,
        aic=result.aic,
        converged=result.converged,
        warnings=result.warnings,
    )


@dataclass
class ValidationFit:
    result: SarimaResult
    selection_mode: str
    transform: str
    inner_mape: float | None


def fit_validation_sarima(
    values: list[float],
    horizon: int,
    seasonal_period: int,
    start_period: str,
    selection_mode: str = "aic",
    inner_holdout: int = 4,
    use_log1p: bool = False,
) -> ValidationFit:
    """Fit SARIMA without using the final thesis hold-out for model selection.

    Baseline mode reproduces AIC selection. Tuned mode creates an additional
    chronological split inside the training set and ranks candidates by that
    training-only MAPE (MAE is the fallback/tiebreaker). The final five-month
    hold-out is not inspected until after the selected model is refit.
    """
    if len(values) < 19:
        raise ValueError(
            "Thesis retrospective SARIMA validation requires at least 19 training observations."
        )

    series = pd.Series(
        values,
        index=pd.period_range(
            start=start_period,
            periods=len(values),
            freq="M",
        ).to_timestamp(),
        dtype="float64",
    )

    if selection_mode == "aic":
        deadline = monotonic() + _validation_timeout_seconds()
        best: SarimaResult | None = None
        failures: list[str] = []
        for order, seasonal in CANDIDATES:
            seasonal_order = (
                seasonal[0],
                seasonal[1],
                seasonal[2],
                seasonal_period,
            )
            try:
                candidate = _fit_variant(
                    series,
                    horizon,
                    order,
                    seasonal_order,
                    deadline,
                    "raw",
                )
                if best is None or candidate.aic < best.aic:
                    best = candidate
            except Exception as exc:  # noqa: BLE001
                failures.append(f"{order}{seasonal_order}: {exc}")

        if best is None:
            raise ValueError(
                "; ".join(failures[-3:])
                or "No SARIMA validation candidate produced a usable forecast."
            )
        return ValidationFit(
            result=best,
            selection_mode="aic",
            transform="raw",
            inner_mape=None,
        )

    if inner_holdout <= 0 or inner_holdout >= len(values):
        raise ValueError("inner hold-out must be positive and smaller than the training set")

    inner_train = series.iloc[:-inner_holdout]
    inner_actual = series.iloc[-inner_holdout:].to_numpy(dtype=float)
    if len(inner_train) < seasonal_period + 2:
        raise ValueError(
            "inner training window is too short for annual-seasonal SARIMA selection"
        )

    transforms = ("raw", "log1p") if use_log1p else ("raw",)
    ranked: list[
        tuple[
            float,
            float,
            float,
            tuple[int, int, int],
            tuple[int, int, int, int],
            str,
        ]
    ] = []
    failures: list[str] = []
    deadline = monotonic() + _validation_timeout_seconds()

    for order, seasonal in VALIDATION_CANDIDATES:
        seasonal_order = (
            seasonal[0],
            seasonal[1],
            seasonal[2],
            seasonal_period,
        )
        for transform in transforms:
            try:
                candidate = _fit_variant(
                    inner_train,
                    inner_holdout,
                    order,
                    seasonal_order,
                    deadline,
                    transform,
                )
                inner_forecast = np.asarray(candidate.forecast, dtype=float)
                inner_metrics = metric_bundle(inner_actual, inner_forecast)
                inner_mape = inner_metrics["mape"]
                score = (
                    float(inner_mape)
                    if inner_mape is not None
                    else float(inner_metrics["mae"]) * 1000.0
                )
                ranked.append(
                    (
                        score,
                        float(inner_metrics["mae"]),
                        float(candidate.aic),
                        order,
                        seasonal_order,
                        transform,
                    )
                )
            except Exception as exc:  # noqa: BLE001
                failures.append(f"{order}{seasonal_order}/{transform}: {exc}")

    if not ranked:
        raise ValueError(
            "; ".join(failures[-3:])
            or "No SARIMA candidate completed training-only model selection."
        )

    ranked.sort(key=lambda row: (row[0], row[1], row[2], row[3], row[4], row[5]))

    refit_failures: list[str] = []
    refit_deadline = monotonic() + _validation_timeout_seconds()
    for score, _mae, _aic, order, seasonal_order, transform in ranked:
        try:
            result = _fit_variant(
                series,
                horizon,
                order,
                seasonal_order,
                refit_deadline,
                transform,
            )
            return ValidationFit(
                result=result,
                selection_mode="inner-mape",
                transform=transform,
                inner_mape=score,
            )
        except Exception as exc:  # noqa: BLE001
            refit_failures.append(f"{order}{seasonal_order}/{transform}: {exc}")

    raise ValueError(
        "; ".join(refit_failures[-3:])
        or "No training-selected SARIMA candidate could be refit."
    )

def metric_bundle(actual: np.ndarray, forecast: np.ndarray) -> dict[str, Any]:
    actual = np.asarray(actual, dtype=float)
    forecast = np.asarray(forecast, dtype=float)

    if actual.shape != forecast.shape or actual.size == 0:
        raise ValueError("Actual and forecast arrays must be non-empty and have identical shapes.")

    mae_sklearn = float(mean_absolute_error(actual, forecast))
    rmse_sklearn = float(root_mean_squared_error(actual, forecast))

    nonzero_mask = actual != 0
    mape_sklearn: float | None = None
    if bool(nonzero_mask.any()):
        mape_sklearn = float(
            mean_absolute_percentage_error(actual[nonzero_mask], forecast[nonzero_mask]) * 100
        )

    residual = actual - forecast
    mae_manual = float(np.mean(np.abs(residual)))
    rmse_manual = float(np.sqrt(np.mean(np.square(residual))))
    mape_manual: float | None = None
    if bool(nonzero_mask.any()):
        mape_manual = float(
            np.mean(np.abs(residual[nonzero_mask] / actual[nonzero_mask])) * 100
        )

    verification = {
        "mae": bool(np.isclose(mae_sklearn, mae_manual, rtol=1e-10, atol=1e-10)),
        "rmse": bool(np.isclose(rmse_sklearn, rmse_manual, rtol=1e-10, atol=1e-10)),
        "mape": (
            mape_sklearn is None
            and mape_manual is None
            or (
                mape_sklearn is not None
                and mape_manual is not None
                and bool(np.isclose(mape_sklearn, mape_manual, rtol=1e-10, atol=1e-10))
            )
        ),
    }

    return {
        "mae": mae_sklearn,
        "rmse": rmse_sklearn,
        "mape": mape_sklearn,
        "manual_mae": mae_manual,
        "manual_rmse": rmse_manual,
        "manual_mape": mape_manual,
        "mape_valid_observations": int(nonzero_mask.sum()),
        "zero_actual_observations": int((~nonzero_mask).sum()),
        "verification": verification,
    }


def study_accuracy_proxy(mape: float | None) -> float | None:
    """Return the project's derived 100-MAPE score for target tracking.

    This is intentionally labelled a study-specific proxy rather than a standard
    forecasting metric. MAE, MAPE, and RMSE remain the primary validation metrics.
    """
    if mape is None:
        return None
    return max(0.0, 100.0 - float(mape))


def git_sha() -> str | None:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.SubprocessError):
        return None


def load_input(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    missing = sorted(REQUIRED_COLUMNS.difference(frame.columns))
    if missing:
        raise ValueError(f"Input CSV is missing required column(s): {', '.join(missing)}")

    frame = frame.copy()
    frame["product_id"] = frame["product_id"].astype(str)
    frame["product_name"] = frame["product_name"].astype(str)
    frame["category"] = frame["category"].astype(str)
    frame["period"] = frame["period"].astype(str)
    frame["quantity_sold"] = pd.to_numeric(frame["quantity_sold"], errors="raise")

    if not np.isfinite(frame["quantity_sold"].to_numpy(dtype=float)).all():
        raise ValueError("quantity_sold contains non-finite values.")
    if (frame["quantity_sold"] < 0).any():
        raise ValueError("quantity_sold contains negative values.")

    frame["_period"] = pd.PeriodIndex(frame["period"], freq="M")
    return frame.sort_values(["product_id", "_period"]).reset_index(drop=True)


def validate_product(
    group: pd.DataFrame,
    holdout: int,
    min_train: int,
    seasonal_period: int,
    selection_mode: str,
    inner_holdout: int,
    use_log1p: bool,
) -> tuple[ProductResult, list[dict[str, Any]]]:
    group = group.sort_values("_period").reset_index(drop=True)
    product_id = str(group.iloc[0]["product_id"])
    product_name = str(group.iloc[0]["product_name"])
    category = str(group.iloc[0]["category"])

    if not ensure_continuous_months(group["period"]):
        raise ValueError("monthly series is not chronological, unique, and continuous")

    minimum_required = min_train + holdout
    if len(group) < minimum_required:
        raise ValueError(
            f"requires at least {minimum_required} observations ({min_train} training + {holdout} testing); found {len(group)}"
        )

    train = group.iloc[:-holdout].copy()
    test = group.iloc[-holdout:].copy()

    if len(train) < min_train:
        raise ValueError(f"training set has only {len(train)} observations")

    train_values = train["quantity_sold"].to_numpy(dtype=float)
    actual = test["quantity_sold"].to_numpy(dtype=float)

    fitted = fit_validation_sarima(
        train_values.tolist(),
        horizon=holdout,
        seasonal_period=seasonal_period,
        start_period=str(train.iloc[0]["period"]),
        selection_mode=selection_mode,
        inner_holdout=inner_holdout,
        use_log1p=use_log1p,
    )
    result = fitted.result
    forecast = np.asarray(result.forecast, dtype=float)

    metrics = metric_bundle(actual, forecast)
    if not all(metrics["verification"].values()):
        raise RuntimeError("independent metric cross-check failed")

    detailed_rows: list[dict[str, Any]] = []
    for index, (_, row) in enumerate(test.iterrows()):
        actual_value = float(row["quantity_sold"])
        forecast_value = float(forecast[index])
        residual = actual_value - forecast_value
        detailed_rows.append(
            {
                "product_id": product_id,
                "product_name": product_name,
                "category": category,
                "period": str(row["period"]),
                "actual": actual_value,
                "forecast": forecast_value,
                "residual": residual,
                "absolute_error": abs(residual),
                "squared_error": residual * residual,
                "absolute_percentage_error": (
                    abs(residual / actual_value) * 100 if actual_value != 0 else None
                ),
                "order": str(tuple(result.order)),
                "seasonal_order": str(tuple(result.seasonal_order)),
                "aic": result.aic,
                "converged": result.converged,
                "selection_mode": fitted.selection_mode,
                "transform": fitted.transform,
                "inner_mape": fitted.inner_mape,
            }
        )

    product_result = ProductResult(
        product_id=product_id,
        product_name=product_name,
        category=category,
        observations=len(group),
        training_observations=len(train),
        testing_observations=len(test),
        training_start=str(train.iloc[0]["period"]),
        training_end=str(train.iloc[-1]["period"]),
        testing_start=str(test.iloc[0]["period"]),
        testing_end=str(test.iloc[-1]["period"]),
        order=str(tuple(result.order)),
        seasonal_order=str(tuple(result.seasonal_order)),
        aic=float(result.aic),
        converged=bool(result.converged),
        mae=float(metrics["mae"]),
        mape=float(metrics["mape"]) if metrics["mape"] is not None else None,
        rmse=float(metrics["rmse"]),
        mape_valid_observations=int(metrics["mape_valid_observations"]),
        zero_actual_observations=int(metrics["zero_actual_observations"]),
        selection_mode=fitted.selection_mode,
        transform=fitted.transform,
        inner_mape=(float(fitted.inner_mape) if fitted.inner_mape is not None else None),
    )
    return product_result, detailed_rows


def select_representative(
    product_metrics: pd.DataFrame, requested_product_id: str | None
) -> str:
    if requested_product_id is not None:
        matches = product_metrics[product_metrics["product_id"] == requested_product_id]
        if matches.empty:
            raise ValueError(
                f"Requested plot product {requested_product_id!r} is not in successful validation results."
            )
        return requested_product_id

    with_mape = product_metrics.dropna(subset=["mape"]).sort_values(
        ["mape", "product_id"]
    )
    if not with_mape.empty:
        target = float(median(with_mape["mape"].astype(float).tolist()))
        ranked = with_mape.assign(distance=(with_mape["mape"] - target).abs()).sort_values(
            ["distance", "product_id"]
        )
        return str(ranked.iloc[0]["product_id"])

    ranked = product_metrics.sort_values(["mae", "product_id"])
    return str(ranked.iloc[len(ranked) // 2]["product_id"])


def save_metric_figures(summary: dict[str, Any], output: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4.5))
    labels = ["MAE", "RMSE"]
    values = [summary["mae"], summary["rmse"]]
    bars = ax.bar(labels, values)
    ax.set_ylabel("Units of monthly quantity sold")
    ax.set_title("SARIMA Forecast Error: MAE and RMSE")
    ax.bar_label(bars, fmt="%.4f")
    fig.tight_layout()
    fig.savefig(output / "mae_rmse_units.png", dpi=180)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4.5))
    if summary["mape"] is None:
        ax.text(0.5, 0.5, "MAPE unavailable\n(no non-zero actual observations)", ha="center", va="center")
        ax.set_axis_off()
    else:
        bars = ax.bar(["MAPE"], [summary["mape"]])
        ax.set_ylabel("Percentage error (%)")
        ax.set_title("SARIMA Mean Absolute Percentage Error")
        ax.bar_label(bars, fmt="%.4f%%")
    fig.tight_layout()
    fig.savefig(output / "mape_percentage.png", dpi=180)
    plt.close(fig)


def save_forecast_figures(
    detailed: pd.DataFrame,
    representative_id: str,
    output: Path,
) -> str:
    overall = (
        detailed.groupby("period", as_index=False)[["actual", "forecast"]]
        .sum()
        .sort_values("period")
    )
    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.plot(overall["period"], overall["actual"], marker="o", label="Actual")
    ax.plot(overall["period"], overall["forecast"], marker="o", label="SARIMA Forecast")
    ax.set_xlabel("Testing month")
    ax.set_ylabel("Aggregated quantity sold")
    ax.set_title("Actual vs Forecasted Demand Across Validated Products")
    ax.legend()
    ax.tick_params(axis="x", rotation=45)
    fig.tight_layout()
    fig.savefig(output / "actual_vs_forecast_overall.png", dpi=180)
    plt.close(fig)

    representative = detailed[detailed["product_id"] == representative_id].sort_values("period")
    representative_name = str(representative.iloc[0]["product_name"])

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.plot(representative["period"], representative["actual"], marker="o", label="Actual")
    ax.plot(
        representative["period"],
        representative["forecast"],
        marker="o",
        label="SARIMA Forecast",
    )
    ax.set_xlabel("Testing month")
    ax.set_ylabel("Quantity sold")
    ax.set_title(f"Actual vs Forecast: {representative_name}")
    ax.legend()
    ax.tick_params(axis="x", rotation=45)
    fig.tight_layout()
    fig.savefig(output / "actual_vs_forecast_representative.png", dpi=180)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.axhline(0, linewidth=1)
    ax.plot(
        representative["period"],
        representative["residual"],
        marker="o",
    )
    ax.set_xlabel("Testing month")
    ax.set_ylabel("Residual (Actual - Forecast)")
    ax.set_title(f"Residual Behavior: {representative_name}")
    ax.tick_params(axis="x", rotation=45)
    fig.tight_layout()
    fig.savefig(output / "residual_plot_representative.png", dpi=180)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(detailed["residual"].astype(float), bins=min(20, max(5, len(detailed) // 10)))
    ax.axvline(0, linewidth=1)
    ax.set_xlabel("Residual (Actual - Forecast)")
    ax.set_ylabel("Observation count")
    ax.set_title("Residual Distribution Across Validated Product-Months")
    fig.tight_layout()
    fig.savefig(output / "residual_distribution.png", dpi=180)
    plt.close(fig)

    return representative_name


def main() -> int:
    args = parse_args()
    input_path = (REPO_ROOT / args.input).resolve() if not Path(args.input).is_absolute() else Path(args.input)
    output = (REPO_ROOT / args.output).resolve() if not Path(args.output).is_absolute() else Path(args.output)

    if args.holdout <= 0:
        raise ValueError("--holdout must be greater than zero.")
    if args.min_train < 19:
        raise ValueError("--min-train must be at least 19 for the frozen thesis retrospective protocol.")
    if args.seasonal_period <= 1:
        raise ValueError("--seasonal-period must be greater than one.")
    if args.inner_holdout <= 0:
        raise ValueError("--inner-holdout must be greater than zero.")
    if not 0.0 < args.target_accuracy <= 100.0:
        raise ValueError("--target-accuracy must be greater than 0 and at most 100.")
    if not input_path.exists():
        raise FileNotFoundError(
            f"Validation input not found: {input_path}. Run npm run thesis:sarima:export first."
        )

    output.mkdir(parents=True, exist_ok=True)
    legacy_html = output / "validation_report.html"
    if legacy_html.exists():
        legacy_html.unlink()
    frame = load_input(input_path)

    product_results: list[ProductResult] = []
    detailed_rows: list[dict[str, Any]] = []
    exclusions: list[dict[str, str]] = []

    for product_id, group in frame.groupby("product_id", sort=True):
        try:
            result, rows = validate_product(
                group,
                holdout=args.holdout,
                min_train=args.min_train,
                seasonal_period=args.seasonal_period,
                selection_mode=args.selection_mode,
                inner_holdout=args.inner_holdout,
                use_log1p=args.use_log1p,
            )
            product_results.append(result)
            detailed_rows.extend(rows)
        except Exception as exc:  # noqa: BLE001 - every exclusion is retained as thesis evidence.
            first = group.iloc[0]
            exclusions.append(
                {
                    "product_id": str(product_id),
                    "product_name": str(first["product_name"]),
                    "reason": str(exc),
                }
            )

    exclusions_frame = pd.DataFrame(exclusions, columns=["product_id", "product_name", "reason"])
    exclusions_frame.to_csv(output / "excluded_products.csv", index=False)

    if not product_results:
        metadata = {
            "git_commit": git_sha(),
            "input": str(input_path),
            "input_rows": len(frame),
            "input_products": int(frame["product_id"].nunique()),
            "successful_products": 0,
            "excluded_products": len(exclusions),
            "holdout_months": args.holdout,
            "minimum_training_observations": args.min_train,
            "seasonal_period": args.seasonal_period,
            "status": "FAILED_NO_ELIGIBLE_PRODUCTS",
        }
        (output / "validation_metadata.json").write_text(
            json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
        )
        print(json.dumps(metadata, indent=2))
        return 2

    product_metrics = pd.DataFrame([asdict(result) for result in product_results])
    detailed = pd.DataFrame(detailed_rows)
    product_metrics.to_csv(output / "product_metrics.csv", index=False)
    detailed.to_csv(output / "detailed_calculations.csv", index=False)

    overall = metric_bundle(
        detailed["actual"].to_numpy(dtype=float),
        detailed["forecast"].to_numpy(dtype=float),
    )
    if not all(overall["verification"].values()):
        raise RuntimeError("Overall metric cross-check failed.")

    rounded_mape = round(float(overall["mape"]), 4) if overall["mape"] is not None else None
    accuracy_proxy = study_accuracy_proxy(rounded_mape)
    summary = {
        "mae": round(float(overall["mae"]), 4),
        "mape": rounded_mape,
        "rmse": round(float(overall["rmse"]), 4),
        "study_accuracy_proxy_pct": (
            round(float(accuracy_proxy), 4) if accuracy_proxy is not None else None
        ),
        "target_accuracy_pct": round(float(args.target_accuracy), 4),
        "target_met": (
            bool(accuracy_proxy >= args.target_accuracy)
            if accuracy_proxy is not None
            else False
        ),
        "mape_valid_observations": int(overall["mape_valid_observations"]),
        "zero_actual_observations_excluded_from_mape": int(overall["zero_actual_observations"]),
        "validated_product_month_observations": len(detailed),
        "validated_products": len(product_metrics),
    }
    pd.DataFrame([summary]).to_csv(output / "summary_metrics.csv", index=False)

    representative_id = select_representative(product_metrics, args.plot_product_id)
    save_metric_figures(summary, output)
    representative_name = save_forecast_figures(detailed, representative_id, output)

    metadata = {
        "status": "COMPLETE",
        "git_commit": git_sha(),
        "input": str(input_path),
        "input_rows": len(frame),
        "input_products": int(frame["product_id"].nunique()),
        "successful_products": len(product_metrics),
        "excluded_products": len(exclusions),
        "holdout_months": args.holdout,
        "minimum_training_observations": args.min_train,
        "seasonal_period": args.seasonal_period,
        "selection_mode": args.selection_mode,
        "inner_holdout_months": args.inner_holdout if args.selection_mode == "inner-mape" else None,
        "log1p_variants_enabled": bool(args.use_log1p and args.selection_mode == "inner-mape"),
        "candidate_count": (
            len(VALIDATION_CANDIDATES)
            if args.selection_mode == "inner-mape"
            else len(CANDIDATES)
        ),
        "candidate_family": [
            {
                "order": list(order),
                "seasonal_order": [seasonal[0], seasonal[1], seasonal[2], args.seasonal_period],
            }
            for order, seasonal in (
                VALIDATION_CANDIDATES
                if args.selection_mode == "inner-mape"
                else CANDIDATES
            )
        ],
        "target_accuracy_pct": round(float(args.target_accuracy), 4),
        "study_accuracy_proxy_definition": "100 - MAPE; study-specific target-tracking proxy, not a replacement for standard forecast error metrics.",
        "target_met": summary["target_met"],
        "validation_protocol": "Retrospective chronological hold-out: first 19 verified months train, final 5 verified months test when using defaults.",
        "production_eligibility_rule_unchanged": "Deployed forecasting still requires 24 completed monthly observations for standard SARIMA.",
        "metric_library": "scikit-learn",
        "metric_cross_check": "NumPy formula cross-check; all summary checks passed.",
        "mape_policy": "Actual=0 observations are retained for MAE/RMSE and excluded only from MAPE.",
        "representative_product_id": representative_id,
        "representative_product_name": representative_name,
        "representative_selection": (
            "Explicit --plot-product-id"
            if args.plot_product_id
            else "Successful product whose MAPE is closest to the median product MAPE; product ID breaks ties."
        ),
        "environment": {
            "python": sys.version.split()[0],
            "sarima_fit_timeout_seconds": os.getenv("SARIMA_FIT_TIMEOUT_SECONDS", "default"),
        },
    }
    (output / "validation_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )

    mape_report_text = "N/A" if summary["mape"] is None else f'{summary["mape"]:.4f}%'
    accuracy_report_text = (
        "N/A"
        if summary["study_accuracy_proxy_pct"] is None
        else f'{summary["study_accuracy_proxy_pct"]:.4f}%'
    )

    report_lines = [
        "YSABELLE STORE - SARIMA THESIS VALIDATION",
        "==========================================",
        f"Status: COMPLETE",
        f"Validated products: {summary['validated_products']}",
        f"Excluded products: {len(exclusions)}",
        f"Validated product-month observations: {summary['validated_product_month_observations']}",
        "",
        "MODEL SELECTION",
        f"Selection mode: {args.selection_mode}",
        f"Candidate configurations: {len(VALIDATION_CANDIDATES) if args.selection_mode == 'inner-mape' else len(CANDIDATES)}",
        f"Log1p variants: {'ENABLED' if args.use_log1p and args.selection_mode == 'inner-mape' else 'DISABLED'}",
        (
            f"Inner hold-out: {args.inner_holdout} month(s) inside training only"
            if args.selection_mode == "inner-mape"
            else "Inner hold-out: not used"
        ),
        "",
        "OVERALL HOLD-OUT METRICS",
        f"MAE  : {summary['mae']:.4f} units",
        f"MAPE : {mape_report_text}",
        f"RMSE : {summary['rmse']:.4f} units",
        "",
        "STUDY TARGET TRACKING",
        f"Derived accuracy proxy (100 - MAPE): {accuracy_report_text}",
        f"Target accuracy: {summary['target_accuracy_pct']:.4f}%",
        f"Target status: {'PASS' if summary['target_met'] else 'BELOW TARGET'}",
        "Note: the derived accuracy proxy is a project reporting convention; MAE, MAPE, and RMSE remain the primary forecast metrics.",
        "",
        f"MAPE-valid observations: {summary['mape_valid_observations']}",
        f"Zero-actual observations excluded from MAPE only: {summary['zero_actual_observations_excluded_from_mape']}",
        "",
        "INDEPENDENT CROSS-CHECK",
        f"MAE  : {'PASS' if overall['verification']['mae'] else 'FAIL'}",
        f"MAPE : {'PASS' if overall['verification']['mape'] else 'FAIL'}",
        f"RMSE : {'PASS' if overall['verification']['rmse'] else 'FAIL'}",
        "",
        f"Representative product for product-level figures: {representative_name} ({representative_id})",
        f"Evidence directory: {output}",
    ]
    (output / "validation_report.txt").write_text("\n".join(report_lines) + "\n", encoding="utf-8")

    print("\n".join(report_lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
