-- Additive persisted forecast delivery cache. Existing forecast records remain unchanged.
CREATE TABLE `forecast_batch_cache` (
  `id` VARCHAR(191) NOT NULL,
  `source` ENUM('DATABASE', 'WORKBOOK_FALLBACK', 'EMPTY') NOT NULL,
  `source_version` VARCHAR(64) NOT NULL,
  `database_revision` VARCHAR(64) NOT NULL,
  `forecast_start_month` DATE NOT NULL,
  `status` ENUM('GENERATING', 'READY', 'FAILED', 'SUPERSEDED', 'EMPTY') NOT NULL DEFAULT 'GENERATING',
  `is_active` BOOLEAN NOT NULL DEFAULT false,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `generated_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `failed_at` DATETIME(3) NULL,
  `duration_ms` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `total_product_count` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `successful_product_count` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `fallback_product_count` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `failed_product_count` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `error_code` VARCHAR(80) NULL,
  `generation_metadata` JSON NULL,
  `validation_metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  INDEX `idx_forecast_batches_active_status`(`is_active`, `status`),
  INDEX `idx_forecast_batches_source_version_month`(`source`, `source_version`, `forecast_start_month`, `status`),
  INDEX `idx_forecast_batches_status_started`(`status`, `started_at`),
  INDEX `idx_forecast_batches_generated`(`generated_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `forecast_product_results` (
  `id` VARCHAR(191) NOT NULL,
  `batch_id` VARCHAR(191) NOT NULL,
  `source_product_id` VARCHAR(191) NOT NULL,
  `product_name` VARCHAR(160) NOT NULL,
  `category` VARCHAR(120) NOT NULL,
  `selling_price` DECIMAL(10,2) NOT NULL,
  `result_status` VARCHAR(24) NOT NULL,
  `model_name` VARCHAR(40) NULL,
  `total_historical_2024` DECIMAL(14,3) NOT NULL,
  `total_historical_2025` DECIMAL(14,3) NOT NULL,
  `total_forecast_2026` DECIMAL(14,3) NOT NULL,
  `growth_versus_2025` DECIMAL(14,4) NULL,
  `current_month_forecast_quantity` DECIMAL(14,3) NULL,
  `recent_historical_sales_total` DECIMAL(14,3) NOT NULL,
  `twelve_month_forecast_total` DECIMAL(14,3) NOT NULL,
  `forecast_variance_percentage` DECIMAL(14,4) NULL,
  `warning_count` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `detail_payload` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `uq_forecast_product_batch_source`(`batch_id`, `source_product_id`),
  INDEX `idx_forecast_product_batch_name`(`batch_id`, `product_name`),
  INDEX `idx_forecast_product_batch_category_name`(`batch_id`, `category`, `product_name`),
  INDEX `idx_forecast_product_batch_total_forecast`(`batch_id`, `total_forecast_2026`),
  INDEX `idx_forecast_product_batch_current_forecast`(`batch_id`, `current_month_forecast_quantity`),
  INDEX `idx_forecast_product_batch_recent_sales`(`batch_id`, `recent_historical_sales_total`),
  INDEX `idx_forecast_product_batch_demand`(`batch_id`, `twelve_month_forecast_total`),
  INDEX `idx_forecast_product_batch_growth`(`batch_id`, `growth_versus_2025`),
  PRIMARY KEY (`id`),
  CONSTRAINT `forecast_product_results_batch_fkey` FOREIGN KEY (`batch_id`) REFERENCES `forecast_batch_cache`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
